import type { Metadata } from "next";
import "./globals.css";
import { syne } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Julia Beauty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.className} antialiased`}>{children}</body>
    </html>
  );
}
